# Generated by Django 2.1.3 on 2018-11-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('last_sold', models.DateField()),
                ('shelf_life', models.IntegerField()),
                ('department', models.CharField(choices=[('GROCERY', 'Grocery'), ('PRODUCE', 'Produce'), ('PHARMACY', 'Pharmacy')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('LB', 'lb'), ('EACH', 'each')], max_length=10)),
                ('x_for', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
